---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kernelspecs-pvc 
  namespace: enterprise-gateway
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Mi

